#!/bin/bash

#############################################################################
#  Copyright 2022 Curity AB                                                 #
#                                                                           #
#  Licensed under the Apache License, Version 2.0 (the "License");          #
#  you may not use this file except in compliance with the License.         #
#  You may obtain a copy of the License at                                  #
#                                                                           #
#      http://www.apache.org/licenses/LICENSE-2.0                           #
#                                                                           #
#  Unless required by applicable law or agreed to in writing, software      #
#  distributed under the License is distributed on an "AS IS" BASIS,        #
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. #
#  See the License for the specific language governing permissions and      #
#  limitations under the License.                                           #
#############################################################################

#
# This prevents accidental checkins of sensitive data by Curity developers
#
git diff --cached --name-only | while read FILE; do

  IS_LICENSE_FILE=$(echo "$FILE" | grep -i 'license.json')
  if [ "$IS_LICENSE_FILE" != '' ]; then
      echo "*** Attempting to check a Curity license file into a public GitHub repository ***"
      exit 1
  fi

  IS_XML_FILE=$(echo "$FILE" | grep -i '\.xml$')
  if [ "$IS_XML_FILE" != '' ]; then
    
    LICENSE_KEY=$(cat $FILE | grep 'license-key' | sed -r "s/^(.*)<license-key>(.*)<\/license-key>$/\2/i")
    if [ "$LICENSE_KEY" != '' ]; then

      echo "*** Attempting to check a Curity license into a public GitHub repository ***"
      exit 1
    fi
  fi
done
